	# -*- coding: utf-8 -*-

	# Form implementation generated from reading ui file 'final.ui'
	#
	# Created by: PyQt5 UI code generator 5.15.0
	#
	# WARNING: Any manual changes made to this file will be lost when pyuic5 is
	# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from datetime import datetime
import calendar
from PyQt5.QtWidgets import QApplication, QWidget, QCalendarWidget, QDialog, QDialogButtonBox, QVBoxLayout
from PyQt5.QtCore import QDate
#from connection import connection, cursor, close_connection
import picture
#from psycopg2.extensions import AsIs



class Ui_MainWindow(object):

	#class variables for adding to database
	#DO NOT MOVE
	complete_input = 0
	added_customer = 0

	def setupUi(self, MainWindow):

		'''
		START OF MAIN WINDOW
		'''

		MainWindow.setObjectName("MainWindow")
		MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
		MainWindow.setEnabled(True)
		MainWindow.resize(1920, 1080)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
		MainWindow.setSizePolicy(sizePolicy)
		MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
		MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
		MainWindow.setSizeIncrement(QtCore.QSize(15, 14))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
		brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
		brush = QtGui.QBrush(QtGui.QColor(114, 114, 114))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
		brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
		brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
		brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
		brush = QtGui.QBrush(QtGui.QColor(114, 114, 114))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
		brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
		brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
		brush = QtGui.QBrush(QtGui.QColor(114, 114, 114))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
		brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
		brush = QtGui.QBrush(QtGui.QColor(114, 114, 114))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
		brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
		brush = QtGui.QBrush(QtGui.QColor(114, 114, 114))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
		brush = QtGui.QBrush(QtGui.QColor(114, 114, 114))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
		brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
		brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
		MainWindow.setPalette(palette)
		MainWindow.setAutoFillBackground(False)
		
		#central widget
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		'''
		END OF MAIN WINDOW
		'''

		'''
		START OF Font FORMATTING
		'''

		SmallKhmerFont = QtGui.QFont()
		SmallKhmerFont.setFamily("KhmerOS")
		SmallKhmerFont.setPointSize(20)

		BigKhmerFont = QtGui.QFont()
		BigKhmerFont.setFamily("KhmerOS")
		BigKhmerFont.setPointSize(30)

		ENGFont = QtGui.QFont()
		ENGFont.setFamily("Palatino Linotype")
		ENGFont.setPointSize(10)

		'''
		END OF Font FORMATTING
		'''
	
		'''
		START OF Customer BOX 
		'''

		#CustomerTitle 
		self.CustomerInfoTitle = QtWidgets.QLabel(self.centralwidget)
		self.CustomerInfoTitle.setGeometry(QtCore.QRect(270, 30, 211, 51))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CustomerInfoTitle.sizePolicy().hasHeightForWidth())
		self.CustomerInfoTitle.setSizePolicy(sizePolicy)
		self.CustomerInfoTitle.setFont(BigKhmerFont)
		self.CustomerInfoTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CustomerInfoTitle.setAutoFillBackground(False)
		self.CustomerInfoTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CustomerInfoTitle.setObjectName("CustomerInfoTitle")


		#CustomerAddress
		self.AddressLabel = QtWidgets.QLabel(self.centralwidget)
		self.AddressLabel.setGeometry(QtCore.QRect(190, 150, 111, 31))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.AddressLabel.sizePolicy().hasHeightForWidth())
		self.AddressLabel.setSizePolicy(sizePolicy)
		self.AddressLabel.setFont(SmallKhmerFont)
		self.AddressLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.AddressLabel.setAutoFillBackground(False)
		self.AddressLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.AddressLabel.setObjectName("AddressLabel")

		#CustomerName
		self.CustomerNameLabel = QtWidgets.QLabel(self.centralwidget)
		self.CustomerNameLabel.setGeometry(QtCore.QRect(190, 68, 81, 31))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CustomerNameLabel.sizePolicy().hasHeightForWidth())
		self.CustomerNameLabel.setSizePolicy(sizePolicy)
		self.CustomerNameLabel.setFont(SmallKhmerFont)
		self.CustomerNameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CustomerNameLabel.setAutoFillBackground(False)
		self.CustomerNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CustomerNameLabel.setObjectName("CustomerNameLabel")



		#CustomerTelephone
		self.PhoneLabel = QtWidgets.QLabel(self.centralwidget)
		self.PhoneLabel.setEnabled(True)
		self.PhoneLabel.setGeometry(QtCore.QRect(190, 110, 121, 31))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.PhoneLabel.sizePolicy().hasHeightForWidth())
		self.PhoneLabel.setSizePolicy(sizePolicy)
		self.PhoneLabel.setFont(SmallKhmerFont)
		self.PhoneLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.PhoneLabel.setAutoFillBackground(False)
		self.PhoneLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.PhoneLabel.setObjectName("PhoneLabel")
		
		#line edits for CUSTOMER
		self.CustomerNameBox = QtWidgets.QLineEdit(self.centralwidget)
		self.CustomerNameBox.setGeometry(QtCore.QRect(340, 70, 161, 31))
		self.CustomerNameBox.setFont(SmallKhmerFont)
		self.CustomerNameBox.setObjectName("CustomerNameBox")

		self.PhoneBox = QtWidgets.QLineEdit(self.centralwidget)
		self.PhoneBox.setGeometry(QtCore.QRect(340, 110, 161, 31))
		self.PhoneBox.setFont(SmallKhmerFont)
		self.PhoneBox.setObjectName("PhoneBox")

		self.AddressBox = QtWidgets.QLineEdit(self.centralwidget)
		self.AddressBox.setGeometry(QtCore.QRect(340, 150, 161, 31))
		self.AddressBox.setFont(SmallKhmerFont)
		self.AddressBox.setObjectName("AddressBox")

		'''
		END OF Customer BOX 
		'''

		'''
		START OF Staff BOX 
		'''
		self.StaffTitle = QtWidgets.QLabel(self.centralwidget)
		self.StaffTitle.setGeometry(QtCore.QRect(260, 240, 201, 51))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.StaffTitle.sizePolicy().hasHeightForWidth())
		self.StaffTitle.setSizePolicy(sizePolicy)
		self.StaffTitle.setFont(BigKhmerFont)
		self.StaffTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.StaffTitle.setAutoFillBackground(False)
		self.StaffTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.StaffTitle.setObjectName("StaffTitle")

		self.StaffNameLabel = QtWidgets.QLabel(self.centralwidget)
		self.StaffNameLabel.setGeometry(QtCore.QRect(190, 300, 71, 31))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.StaffNameLabel.sizePolicy().hasHeightForWidth())
		self.StaffNameLabel.setSizePolicy(sizePolicy)
		self.StaffNameLabel.setFont(SmallKhmerFont)
		self.StaffNameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.StaffNameLabel.setAutoFillBackground(False)
		self.StaffNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.StaffNameLabel.setObjectName("StaffNameLabel")

		
		self.DeadlineLabel = QtWidgets.QLabel(self.centralwidget)
		self.DeadlineLabel.setGeometry(QtCore.QRect(190, 340, 121, 31))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.DeadlineLabel.sizePolicy().hasHeightForWidth())
		self.DeadlineLabel.setSizePolicy(sizePolicy)
		self.DeadlineLabel.setFont(SmallKhmerFont)
		self.DeadlineLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.DeadlineLabel.setAutoFillBackground(False)
		self.DeadlineLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.DeadlineLabel.setObjectName("DeadlineLabel")
		
		self.DateIcon = QtWidgets.QPushButton(self.centralwidget)
		self.DateIcon.setGeometry(QtCore.QRect(308, 340, 40, 40))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.DateIcon.sizePolicy().hasHeightForWidth())
		self.DateIcon.setSizePolicy(sizePolicy)
		self.DateIcon.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.DateIcon.setAutoFillBackground(False)
		self.DateIcon.setObjectName("DateIcon")
		self.DateIcon.setIcon(QtGui.QIcon('calendar.png'))
		size = QtCore.QSize(40, 40)
		self.DateIcon.setIconSize(size)
		

		#user input name of staff
		self.StaffNameBox = QtWidgets.QLineEdit(self.centralwidget)
		self.StaffNameBox.setGeometry(QtCore.QRect(310, 300, 180, 31))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.StaffNameBox.sizePolicy().hasHeightForWidth())
		self.StaffNameBox.setSizePolicy(sizePolicy)
		self.StaffNameBox.setFont(SmallKhmerFont)
		self.StaffNameBox.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.StaffNameBox.setAutoFillBackground(False)
		self.StaffNameBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
		self.StaffNameBox.setText("")
		self.StaffNameBox.setAlignment(QtCore.Qt.AlignCenter)
		self.StaffNameBox.setObjectName("StaffNameBox")

		#label to show date chosen
		self.DeadlineSelectedLabel = QtWidgets.QLabel(self.centralwidget)
		self.DeadlineSelectedLabel.setGeometry(QtCore.QRect(370, 341, 120, 40))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.DeadlineSelectedLabel.sizePolicy().hasHeightForWidth())
		self.DeadlineSelectedLabel.setSizePolicy(sizePolicy)
		self.DeadlineSelectedLabel.setFont(SmallKhmerFont)
		self.DeadlineSelectedLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.DeadlineSelectedLabel.setAutoFillBackground(False)
		self.DeadlineSelectedLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.DeadlineSelectedLabel.setObjectName("DeadlineSelectedLabel")

		#label to send date to database
		self.DeadlineBox = QtWidgets.QLabel(self.centralwidget)
		self.DeadlineBox.setGeometry(QtCore.QRect(370, 341, 1, 1))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.DeadlineBox.sizePolicy().hasHeightForWidth())
		self.DeadlineBox.setSizePolicy(sizePolicy)
		self.DeadlineBox.setFont(SmallKhmerFont)
		self.DeadlineBox.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.DeadlineBox.setAutoFillBackground(False)
		self.DeadlineBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.DeadlineBox.setObjectName("DeadlineBox")

		'''
		END OF Staff BOX 
		'''

		'''
		START OF CUSTOMER PREFERENCES BOX
		'''
		self.CustomerPreferencesTitle = QtWidgets.QLabel(self.centralwidget)
		self.CustomerPreferencesTitle.setGeometry(QtCore.QRect(650, 27, 150, 51))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CustomerPreferencesTitle.sizePolicy().hasHeightForWidth())
		self.CustomerPreferencesTitle.setSizePolicy(sizePolicy)
		self.CustomerPreferencesTitle.setFont(BigKhmerFont)
		self.CustomerPreferencesTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CustomerPreferencesTitle.setAutoFillBackground(False)
		self.CustomerPreferencesTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CustomerPreferencesTitle.setObjectName("CustomerPreferencesTitle")

		self.ColorLabel = QtWidgets.QLabel(self.centralwidget)
		self.ColorLabel.setGeometry(QtCore.QRect(580, 100, 91, 51))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.ColorLabel.sizePolicy().hasHeightForWidth())
		self.ColorLabel.setSizePolicy(sizePolicy)
		self.ColorLabel.setFont(SmallKhmerFont)
		self.ColorLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.ColorLabel.setAutoFillBackground(False)
		self.ColorLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.ColorLabel.setObjectName("ColorLabel")

		self.StyleLabel = QtWidgets.QLabel(self.centralwidget)
		self.StyleLabel.setGeometry(QtCore.QRect(580, 150, 81, 31))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.StyleLabel.sizePolicy().hasHeightForWidth())
		self.StyleLabel.setSizePolicy(sizePolicy)
		self.StyleLabel.setFont(SmallKhmerFont)
		self.StyleLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.StyleLabel.setAutoFillBackground(False)
		self.StyleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.StyleLabel.setObjectName("StyleLabel")


		self.MaterialsLabel = QtWidgets.QLabel(self.centralwidget)
		self.MaterialsLabel.setGeometry(QtCore.QRect(580, 60, 91, 51))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.MaterialsLabel.sizePolicy().hasHeightForWidth())
		self.MaterialsLabel.setSizePolicy(sizePolicy)
		self.MaterialsLabel.setFont(SmallKhmerFont)
		self.MaterialsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.MaterialsLabel.setAutoFillBackground(False)
		self.MaterialsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.MaterialsLabel.setObjectName("MaterialsLabel")

		#user inputs
		self.ColorBox = QtWidgets.QLineEdit(self.centralwidget)
		self.ColorBox.setGeometry(QtCore.QRect(680, 69, 171, 31))
		self.ColorBox.setFont(SmallKhmerFont)
		self.ColorBox.setObjectName("ColorBox")

		self.StyleBox = QtWidgets.QLineEdit(self.centralwidget)
		self.StyleBox.setGeometry(QtCore.QRect(680, 109, 171, 31))
		self.StyleBox.setFont(SmallKhmerFont)
		self.StyleBox.setObjectName("StyleBox")
		self.MaterialBox = QtWidgets.QLineEdit(self.centralwidget)
		self.MaterialBox.setGeometry(QtCore.QRect(680, 149, 171, 31))
		self.MaterialBox.setFont(SmallKhmerFont)
		self.MaterialBox.setObjectName("MaterialBox")

		'''
		END OF CUSTOMER PREFERENCES BOX
		'''

		
		'''
		START OF CUSTOMER PREFERENCES BOX
		'''
		self.SpecialReqTitle = QtWidgets.QLabel(self.centralwidget)
		self.SpecialReqTitle.setGeometry(QtCore.QRect(650, 240, 171, 51))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.SpecialReqTitle.sizePolicy().hasHeightForWidth())
		self.SpecialReqTitle.setSizePolicy(sizePolicy)
		self.SpecialReqTitle.setFont(BigKhmerFont)
		self.SpecialReqTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.SpecialReqTitle.setAutoFillBackground(False)
		self.SpecialReqTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.SpecialReqTitle.setObjectName("SpecialReqTitle")

		self.SpecialReqBox = QtWidgets.QPlainTextEdit(self.centralwidget)
		self.SpecialReqBox.setFont(SmallKhmerFont)
		self.SpecialReqBox.setGeometry(QtCore.QRect(580, 290, 271, 111))
		self.SpecialReqBox.setObjectName("SpecialReqBox")

		'''
		END OF CUSTOMER PREFERENCES BOX
		'''

		'''
		START OF MEASUREMENTS BOX
		'''

		self.MeasurementTitle = QtWidgets.QLabel(self.centralwidget)
		self.MeasurementTitle.setGeometry(QtCore.QRect(20, 410, 250, 51))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.MeasurementTitle.sizePolicy().hasHeightForWidth())
		self.MeasurementTitle.setSizePolicy(sizePolicy)
		self.MeasurementTitle.setFont(BigKhmerFont)
		self.MeasurementTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.MeasurementTitle.setAutoFillBackground(False)
		self.MeasurementTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.MeasurementTitle.setObjectName("MeasurementTitle")

		
		
		self.Cancel = QtWidgets.QPushButton(self.centralwidget)
		self.Cancel.setGeometry(QtCore.QRect(1450, 850, 75, 23))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.Cancel.sizePolicy().hasHeightForWidth())
		self.Cancel.setSizePolicy(sizePolicy)
		self.Cancel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.Cancel.setAutoFillBackground(False)
		self.Cancel.setObjectName("Cancel")

		self.Submit = QtWidgets.QPushButton(self.centralwidget)
		self.Submit.setGeometry(QtCore.QRect(1370, 850, 75, 23))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.Submit.sizePolicy().hasHeightForWidth())
		self.Submit.setSizePolicy(sizePolicy)
		self.Submit.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.Submit.setAutoFillBackground(False)
		self.Submit.setObjectName("Submit")

		self.PriceBox = QtWidgets.QLineEdit(self.centralwidget)
		self.PriceBox.setGeometry(QtCore.QRect(1370, 700, 101, 61))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.PriceBox.sizePolicy().hasHeightForWidth())
		self.PriceBox.setSizePolicy(sizePolicy)
		self.PriceBox.setFont(SmallKhmerFont)
		self.PriceBox.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.PriceBox.setAutoFillBackground(False)
		self.PriceBox.setAlignment(QtCore.Qt.AlignCenter)
		self.PriceBox.setObjectName("PriceBox")

		self.PriceLabel = QtWidgets.QLabel(self.centralwidget)
		self.PriceLabel.setGeometry(QtCore.QRect(1300, 710, 71, 41))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.PriceLabel.sizePolicy().hasHeightForWidth())
		self.PriceLabel.setSizePolicy(sizePolicy)
		self.PriceLabel.setFont(BigKhmerFont)
		self.PriceLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.PriceLabel.setAutoFillBackground(False)
		self.PriceLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.PriceLabel.setObjectName("PriceLabel")


		self.ShirtDressSkirtBox = QtWidgets.QGroupBox(self.centralwidget)
		self.ShirtDressSkirtBox.setGeometry(QtCore.QRect(0, 450, 791, 521))
		self.ShirtDressSkirtBox.setFont(BigKhmerFont)
		self.ShirtDressSkirtBox.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.ShirtDressSkirtBox.setObjectName("ShirtDressSkirtBox")

		self.gridLayout = QtWidgets.QGridLayout(self.ShirtDressSkirtBox)
		self.gridLayout.setObjectName("gridLayout")

		self.AroundBustBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.AroundBustBox.setAlignment(QtCore.Qt.AlignCenter)
		self.AroundBustBox.setObjectName("AroundBustBox")
		self.gridLayout.addWidget(self.AroundBustBox, 4, 4, 1, 1)

		self.NeckArmHoldBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.NeckArmHoldBox.setAlignment(QtCore.Qt.AlignCenter)
		self.NeckArmHoldBox.setObjectName("NeckArmHoldBox")
		self.gridLayout.addWidget(self.NeckArmHoldBox, 1, 4, 1, 1)
		
		self.WaistBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.WaistBox.setAlignment(QtCore.Qt.AlignCenter)
		self.WaistBox.setObjectName("WaistBox")
		self.gridLayout.addWidget(self.WaistBox, 6, 4, 1, 1)

		self.ABBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.ABBox.setAlignment(QtCore.Qt.AlignCenter)
		self.ABBox.setObjectName("ABBox")
		self.gridLayout.addWidget(self.ABBox, 0, 4, 1, 1)

		self.DressSkirtWaistLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		self.DressSkirtWaistLabel.setObjectName("DressSkirtWaistLabel")
		self.DressSkirtWaistLabel.setFont(SmallKhmerFont)
		self.gridLayout.addWidget(self.DressSkirtWaistLabel, 6, 3, 1, 1, QtCore.Qt.AlignHCenter)


		self.UpperHipsLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		self.UpperHipsLabel.setFont(SmallKhmerFont)
		self.UpperHipsLabel.setObjectName("UpperHipsLabel")
		self.gridLayout.addWidget(self.UpperHipsLabel, 3, 6, 1, 1)
		
		self.CmUpperHips = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmUpperHips.sizePolicy().hasHeightForWidth())
		self.CmUpperHips.setSizePolicy(sizePolicy)
		self.CmUpperHips.setFont(ENGFont)
		self.CmUpperHips.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmUpperHips.setAutoFillBackground(False)
		self.CmUpperHips.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmUpperHips.setObjectName("CmUpperHips")
		self.gridLayout.addWidget(self.CmUpperHips, 3, 8, 1, 1)



		self.CmAroundBust = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmAroundBust.sizePolicy().hasHeightForWidth())
		self.CmAroundBust.setSizePolicy(sizePolicy)
		self.CmAroundBust.setFont(ENGFont)
		self.CmAroundBust.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmAroundBust.setAutoFillBackground(False)
		self.CmAroundBust.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmAroundBust.setObjectName("CmAroundBust")
		self.gridLayout.addWidget(self.CmAroundBust, 4, 5, 1, 1)


		self.HipLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		self.HipLabel.setFont(SmallKhmerFont)
		self.HipLabel.setObjectName("HipLabel")
		self.gridLayout.addWidget(self.HipLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)

		self.HipBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.HipBox.setAlignment(QtCore.Qt.AlignCenter)
		self.HipBox.setObjectName("HipBox")
		self.gridLayout.addWidget(self.HipBox, 0, 1, 1, 1)

		
		self.CmCenterFront = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmCenterFront.sizePolicy().hasHeightForWidth())
		self.CmCenterFront.setSizePolicy(sizePolicy)
		self.CmCenterFront.setFont(ENGFont)
		self.CmCenterFront.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmCenterFront.setAutoFillBackground(False)
		self.CmCenterFront.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmCenterFront.setObjectName("CmCenterFront")
		self.gridLayout.addWidget(self.CmCenterFront, 3, 2, 1, 1)

		self.CmNeckArmHold = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmNeckArmHold.sizePolicy().hasHeightForWidth())
		self.CmNeckArmHold.setSizePolicy(sizePolicy)
		self.CmNeckArmHold.setFont(ENGFont)
		self.CmNeckArmHold.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmNeckArmHold.setAutoFillBackground(False)
		self.CmNeckArmHold.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmNeckArmHold.setObjectName("CmNeckArmHold")
		self.gridLayout.addWidget(self.CmNeckArmHold, 1, 5, 1, 1)


		self.NeckArmHoldLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.NeckArmHoldLabel.sizePolicy().hasHeightForWidth())
		self.NeckArmHoldLabel.setSizePolicy(sizePolicy)
		self.NeckArmHoldLabel.setFont(SmallKhmerFont)
		self.NeckArmHoldLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.NeckArmHoldLabel.setAutoFillBackground(False)
		self.NeckArmHoldLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.NeckArmHoldLabel.setObjectName("NeckArmHoldLabel")
		self.gridLayout.addWidget(self.NeckArmHoldLabel, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
		
		
		self.CmAB = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmAB.sizePolicy().hasHeightForWidth())
		self.CmAB.setSizePolicy(sizePolicy)
		self.CmAB.setFont(ENGFont)
		self.CmAB.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmAB.setAutoFillBackground(False)
		self.CmAB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmAB.setObjectName("CmAB")
		self.gridLayout.addWidget(self.CmAB, 0, 5, 1, 1)


		self.CmHip = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmHip.sizePolicy().hasHeightForWidth())
		self.CmHip.setSizePolicy(sizePolicy)
		self.CmHip.setFont(ENGFont)
		self.CmHip.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmHip.setAutoFillBackground(False)
		self.CmHip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmHip.setObjectName("CmHip")
		self.gridLayout.addWidget(self.CmHip, 0, 2, 1, 1)


		self.CmBustHeight = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmBustHeight.sizePolicy().hasHeightForWidth())
		self.CmBustHeight.setSizePolicy(sizePolicy)
		self.CmBustHeight.setFont(ENGFont)
		self.CmBustHeight.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmBustHeight.setAutoFillBackground(False)
		self.CmBustHeight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmBustHeight.setObjectName("CmBustHeight")
		self.gridLayout.addWidget(self.CmBustHeight, 5, 5, 1, 1)

		self.CmAboveBust = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmAboveBust.sizePolicy().hasHeightForWidth())
		self.CmAboveBust.setSizePolicy(sizePolicy)
		self.CmAboveBust.setFont(ENGFont)
		self.CmAboveBust.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmAboveBust.setAutoFillBackground(False)
		self.CmAboveBust.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmAboveBust.setObjectName("CmAboveBust")
		self.gridLayout.addWidget(self.CmAboveBust, 3, 5, 1, 1)

		self.CmSkirtLength = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmSkirtLength.sizePolicy().hasHeightForWidth())
		self.CmSkirtLength.setSizePolicy(sizePolicy)
		self.CmSkirtLength.setFont(ENGFont)
		self.CmSkirtLength.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmSkirtLength.setAutoFillBackground(False)
		self.CmSkirtLength.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmSkirtLength.setObjectName("CmSkirtLength")
		self.gridLayout.addWidget(self.CmSkirtLength, 1, 2, 1, 1)
		self.CmAF = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmAF.sizePolicy().hasHeightForWidth())
		self.CmAF.setSizePolicy(sizePolicy)
		
		self.CmAF.setFont(ENGFont)
		self.CmAF.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmAF.setAutoFillBackground(False)
		self.CmAF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmAF.setObjectName("CmAF")
		self.gridLayout.addWidget(self.CmAF, 6, 2, 1, 1)
		self.CmShoulder = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmShoulder.sizePolicy().hasHeightForWidth())
		self.CmShoulder.setSizePolicy(sizePolicy)
		self.CmShoulder.setFont(ENGFont)
		self.CmShoulder.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmShoulder.setAutoFillBackground(False)
		self.CmShoulder.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmShoulder.setObjectName("CmShoulder")
		self.gridLayout.addWidget(self.CmShoulder, 5, 2, 1, 1)
		
		self.ShoulderLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.ShoulderLabel.sizePolicy().hasHeightForWidth())
		self.ShoulderLabel.setSizePolicy(sizePolicy)
		self.ShoulderLabel.setFont(SmallKhmerFont)
		self.ShoulderLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.ShoulderLabel.setAutoFillBackground(False)
		self.ShoulderLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.ShoulderLabel.setObjectName("ShoulderLabel")
		self.gridLayout.addWidget(self.ShoulderLabel, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)


		self.CmCenterBack = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmCenterBack.sizePolicy().hasHeightForWidth())
		self.CmCenterBack.setSizePolicy(sizePolicy)
		self.CmCenterBack.setFont(ENGFont)
		self.CmCenterBack.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmCenterBack.setAutoFillBackground(False)
		self.CmCenterBack.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmCenterBack.setObjectName("CmCenterBack")
		self.gridLayout.addWidget(self.CmCenterBack, 4, 2, 1, 1)
		self.CenterFrontLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CenterFrontLabel.sizePolicy().hasHeightForWidth())
		self.CenterFrontLabel.setSizePolicy(sizePolicy)
		self.CenterFrontLabel.setFont(SmallKhmerFont)
		self.CenterFrontLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CenterFrontLabel.setAutoFillBackground(False)
		self.CenterFrontLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CenterFrontLabel.setObjectName("CenterFrontLabel")
		self.gridLayout.addWidget(self.CenterFrontLabel, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
		self.CmDressSkirtWaist = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmDressSkirtWaist.sizePolicy().hasHeightForWidth())
		self.CmDressSkirtWaist.setSizePolicy(sizePolicy)
		
		self.CmDressSkirtWaist.setFont(ENGFont)
		self.CmDressSkirtWaist.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmDressSkirtWaist.setAutoFillBackground(False)
		self.CmDressSkirtWaist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmDressSkirtWaist.setObjectName("CmDressSkirtWaist")
		self.gridLayout.addWidget(self.CmDressSkirtWaist, 6, 5, 1, 1)
		self.SleeveLengthLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.SleeveLengthLabel.sizePolicy().hasHeightForWidth())
		self.SleeveLengthLabel.setSizePolicy(sizePolicy)
		self.SleeveLengthLabel.setFont(SmallKhmerFont)
		self.SleeveLengthLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.SleeveLengthLabel.setAutoFillBackground(False)
		self.SleeveLengthLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.SleeveLengthLabel.setObjectName("SleeveLengthLabel")
		self.gridLayout.addWidget(self.SleeveLengthLabel, 1, 6, 1, 1, QtCore.Qt.AlignHCenter)
		self.CmSleeveLength = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmSleeveLength.sizePolicy().hasHeightForWidth())
		self.CmSleeveLength.setSizePolicy(sizePolicy)
		
		self.CmSleeveLength.setFont(ENGFont)
		self.CmSleeveLength.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmSleeveLength.setAutoFillBackground(False)
		self.CmSleeveLength.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmSleeveLength.setObjectName("CmSleeveLength")
		self.gridLayout.addWidget(self.CmSleeveLength, 1, 8, 1, 1)

		self.AboveBustLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		self.AboveBustLabel.setFont(SmallKhmerFont)
		self.AboveBustLabel.setObjectName("AboveBustLabel")
		self.gridLayout.addWidget(self.AboveBustLabel, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
		self.CmArmPit = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmArmPit.sizePolicy().hasHeightForWidth())
		self.CmArmPit.setSizePolicy(sizePolicy)
		
		self.CmArmPit.setFont(ENGFont)
		self.CmArmPit.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmArmPit.setAutoFillBackground(False)
		self.CmArmPit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmArmPit.setObjectName("CmArmPit")
		self.gridLayout.addWidget(self.CmArmPit, 0, 8, 1, 1)
		self.ArmpitLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.ArmpitLabel.sizePolicy().hasHeightForWidth())

		self.ArmpitLabel.setSizePolicy(sizePolicy)
		self.ArmpitLabel.setFont(SmallKhmerFont)
		self.ArmpitLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.ArmpitLabel.setAutoFillBackground(False)
		self.ArmpitLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.ArmpitLabel.setObjectName("ArmpitLabel")

		self.gridLayout.addWidget(self.ArmpitLabel, 0, 6, 1, 1, QtCore.Qt.AlignHCenter)
		self.ABLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.ABLabel.sizePolicy().hasHeightForWidth())
		self.ABLabel.setSizePolicy(sizePolicy)
		self.ABLabel.setFont(SmallKhmerFont)
		self.ABLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.ABLabel.setAutoFillBackground(False)
		self.ABLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.ABLabel.setObjectName("ABLabel")
		self.gridLayout.addWidget(self.ABLabel, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
	
		self.AroundBustLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		self.AroundBustLabel.setFont(SmallKhmerFont)
		self.AroundBustLabel.setObjectName("AroundBustLabel")
		self.gridLayout.addWidget(self.AroundBustLabel, 4, 3, 1, 1, QtCore.Qt.AlignHCenter)

		self.BustHeightLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		self.BustHeightLabel.setFont(SmallKhmerFont)
		self.BustHeightLabel.setObjectName("BustHeightLabel")
		self.gridLayout.addWidget(self.BustHeightLabel, 5, 3, 1, 1, QtCore.Qt.AlignHCenter)

		self.AboveBustBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.AboveBustBox.setAlignment(QtCore.Qt.AlignCenter)
		self.AboveBustBox.setObjectName("AboveBustBox")
		self.gridLayout.addWidget(self.AboveBustBox, 3, 4, 1, 1)

		self.CenterFrontBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.CenterFrontBox.setAlignment(QtCore.Qt.AlignCenter)
		self.CenterFrontBox.setObjectName("CenterFrontBox")
		self.gridLayout.addWidget(self.CenterFrontBox, 3, 1, 1, 1)

		self.ShoulderBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.ShoulderBox.setAlignment(QtCore.Qt.AlignCenter)
		self.ShoulderBox.setObjectName("ShoulderBox")
		self.gridLayout.addWidget(self.ShoulderBox, 5, 1, 1, 1)

		self.AFBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.AFBox.setAlignment(QtCore.Qt.AlignCenter)
		self.AFBox.setObjectName("AFBox")
		self.gridLayout.addWidget(self.AFBox, 6, 1, 1, 1)

		self.CenterBackBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.CenterBackBox.setAlignment(QtCore.Qt.AlignCenter)
		self.CenterBackBox.setObjectName("CenterBackBox")
		self.gridLayout.addWidget(self.CenterBackBox, 4, 1, 1, 1)
		

		
		self.UpperHipsBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.UpperHipsBox.setAlignment(QtCore.Qt.AlignCenter)
		self.UpperHipsBox.setObjectName("UpperHipsBox")
		self.gridLayout.addWidget(self.UpperHipsBox, 3, 7, 1, 1)


		
		self.ArmpitBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.ArmpitBox.setAlignment(QtCore.Qt.AlignCenter)
		self.ArmpitBox.setObjectName("ArmpitBox")
		self.gridLayout.addWidget(self.ArmpitBox, 0, 7, 1, 1)

		self.SkirtLengthLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		self.SkirtLengthLabel.setObjectName("SkirtLengthLabel")
		self.SkirtLengthLabel.setFont(SmallKhmerFont)
		self.gridLayout.addWidget(self.SkirtLengthLabel, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)

		self.SkirtLengthBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.SkirtLengthBox.setAlignment(QtCore.Qt.AlignCenter)
		self.SkirtLengthBox.setObjectName("SkirtLengthBox")
		self.gridLayout.addWidget(self.SkirtLengthBox, 1, 1, 1, 1)

		self.SleeveLengthBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.SleeveLengthBox.setAlignment(QtCore.Qt.AlignCenter)
		self.SleeveLengthBox.setObjectName("SleeveLengthBox")
		self.gridLayout.addWidget(self.SleeveLengthBox, 1, 7, 1, 1)

		self.AFLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.AFLabel.sizePolicy().hasHeightForWidth())
		self.AFLabel.setSizePolicy(sizePolicy)
		self.AFLabel.setFont(SmallKhmerFont)
		self.AFLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.AFLabel.setAutoFillBackground(False)
		self.AFLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.AFLabel.setObjectName("AFLabel")
		self.gridLayout.addWidget(self.AFLabel, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
		


		self.CenterBackLabel = QtWidgets.QLabel(self.ShirtDressSkirtBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CenterBackLabel.sizePolicy().hasHeightForWidth())
		self.CenterBackLabel.setSizePolicy(sizePolicy)
		self.CenterBackLabel.setFont(SmallKhmerFont)
		self.CenterBackLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CenterBackLabel.setAutoFillBackground(False)
		self.CenterBackLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CenterBackLabel.setObjectName("CenterBackLabel")
		self.gridLayout.addWidget(self.CenterBackLabel, 4, 0, 1, 1)

		self.BustHeightBox = QtWidgets.QLineEdit(self.ShirtDressSkirtBox)
		self.BustHeightBox.setAlignment(QtCore.Qt.AlignCenter)
		self.BustHeightBox.setObjectName("BustHeightBox")
		self.gridLayout.addWidget(self.BustHeightBox, 5, 4, 1, 1)

		self.line = QtWidgets.QFrame(self.centralwidget)
		self.line.setGeometry(QtCore.QRect(260, 430, 941, 20))
		self.line.setFrameShape(QtWidgets.QFrame.HLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")

		self.PreviewTitle = QtWidgets.QLabel(self.centralwidget)
		self.PreviewTitle.setGeometry(QtCore.QRect(1350, 50, 101, 51))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.PreviewTitle.sizePolicy().hasHeightForWidth())
		self.PreviewTitle.setSizePolicy(sizePolicy)
		self.PreviewTitle.setFont(BigKhmerFont)
		self.PreviewTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.PreviewTitle.setAutoFillBackground(False)
		self.PreviewTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.PreviewTitle.setObjectName("PreviewTitle")

		self.ShirtRadio = QtWidgets.QRadioButton(self.centralwidget)
		self.ShirtRadio.setGeometry(QtCore.QRect(1330, 96, 61, 31))
		self.ShirtRadio.setFont(SmallKhmerFont)
		self.ShirtRadio.setObjectName("ShirtRadio")

		self.DressRadio = QtWidgets.QRadioButton(self.centralwidget)
		self.DressRadio.setGeometry(QtCore.QRect(1400, 96, 61, 31))
		self.DressRadio.setFont(SmallKhmerFont)
		self.DressRadio.setObjectName("DressRadio")
		self.PantRadio = QtWidgets.QRadioButton(self.centralwidget)
		self.PantRadio.setGeometry(QtCore.QRect(1470, 96, 82, 31))
		self.PantRadio.setFont(SmallKhmerFont)
		self.PantRadio.setObjectName("PantRadio")

		self.line_2 = QtWidgets.QFrame(self.centralwidget)
		self.line_2.setGeometry(QtCore.QRect(1190, 0, 20, 961))
		self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		
		self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
		self.textBrowser_4.setGeometry(QtCore.QRect(170, 30, 341, 201))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.textBrowser_4.sizePolicy().hasHeightForWidth())
		self.textBrowser_4.setSizePolicy(sizePolicy)
		self.textBrowser_4.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.textBrowser_4.setAutoFillBackground(False)
		self.textBrowser_4.setInputMethodHints(QtCore.Qt.ImhNone)
		self.textBrowser_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.textBrowser_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.textBrowser_4.setReadOnly(True)
		self.textBrowser_4.setObjectName("textBrowser_4")
		
		self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
		self.textBrowser_5.setGeometry(QtCore.QRect(570, 30, 291, 201))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.textBrowser_5.sizePolicy().hasHeightForWidth())
		self.textBrowser_5.setSizePolicy(sizePolicy)
		self.textBrowser_5.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.textBrowser_5.setAutoFillBackground(False)
		self.textBrowser_5.setInputMethodHints(QtCore.Qt.ImhNone)
		self.textBrowser_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.textBrowser_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.textBrowser_5.setObjectName("textBrowser_5")
		self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
		self.textBrowser_6.setGeometry(QtCore.QRect(170, 240, 341, 171))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.textBrowser_6.sizePolicy().hasHeightForWidth())
		self.textBrowser_6.setSizePolicy(sizePolicy)
		self.textBrowser_6.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.textBrowser_6.setAutoFillBackground(False)
		self.textBrowser_6.setInputMethodHints(QtCore.Qt.ImhNone)
		self.textBrowser_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.textBrowser_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.textBrowser_6.setObjectName("textBrowser_6")
		self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
		self.textBrowser_7.setGeometry(QtCore.QRect(570, 240, 291, 171))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.textBrowser_7.sizePolicy().hasHeightForWidth())
		self.textBrowser_7.setSizePolicy(sizePolicy)
		self.textBrowser_7.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.textBrowser_7.setAutoFillBackground(False)
		self.textBrowser_7.setInputMethodHints(QtCore.Qt.ImhNone)
		self.textBrowser_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.textBrowser_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.textBrowser_7.setObjectName("textBrowser_7")
		self.SkirtRadio = QtWidgets.QRadioButton(self.centralwidget)
		self.SkirtRadio.setGeometry(QtCore.QRect(1260, 96, 61, 31))
		self.SkirtRadio.setFont(SmallKhmerFont)
		self.SkirtRadio.setObjectName("SkirtRadio")

	
	   
		
		self.PantGroupBox = QtWidgets.QGroupBox(self.centralwidget)
		self.PantGroupBox.setGeometry(QtCore.QRect(840, 450, 271, 511))
		self.PantGroupBox.setFont(BigKhmerFont)
		self.PantGroupBox.setObjectName("PantGroupBox")

		self.PantGroupLayout = QtWidgets.QGridLayout(self.PantGroupBox)
		self.PantGroupLayout.setObjectName("PantGroupLayout")


		self.ThighLabel = QtWidgets.QLabel(self.PantGroupBox)
		self.ThighLabel.setFont(SmallKhmerFont)
		self.ThighLabel.setObjectName("ThighLabel")
		self.PantGroupLayout.addWidget(self.ThighLabel, 7, 0, 1, 1)

		self.OutseamLabel = QtWidgets.QLabel(self.PantGroupBox)
		self.OutseamLabel.setFont(SmallKhmerFont)
		self.OutseamLabel.setObjectName("OutseamLabel")
		self.PantGroupLayout.addWidget(self.OutseamLabel, 6, 0, 1, 1)

		self.CalfLabel = QtWidgets.QLabel(self.PantGroupBox)
		self.CalfLabel.setFont(SmallKhmerFont)
		self.CalfLabel.setObjectName("CalfLabel")
		self.PantGroupLayout.addWidget(self.CalfLabel, 8, 0, 1, 1)

		self.InseamLabel = QtWidgets.QLabel(self.PantGroupBox)
		self.InseamLabel.setFont(SmallKhmerFont)
		self.InseamLabel.setObjectName("InseamLabel")
		self.PantGroupLayout.addWidget(self.InseamLabel, 3, 0, 1, 1)
		self.InseamBox = QtWidgets.QLineEdit(self.PantGroupBox)
		self.InseamBox.setAlignment(QtCore.Qt.AlignCenter)
		self.InseamBox.setObjectName("InseamBox")
		self.PantGroupLayout.addWidget(self.InseamBox, 3, 1, 1, 1)
		

		self.OutseamBox = QtWidgets.QLineEdit(self.PantGroupBox)
		self.OutseamBox.setAlignment(QtCore.Qt.AlignCenter)
		self.OutseamBox.setObjectName("OutseamBox")
		self.PantGroupLayout.addWidget(self.OutseamBox, 6, 1, 1, 1)
		
		self.PantHipLabel = QtWidgets.QLabel(self.PantGroupBox)

		self.PantHipLabel.setFont(SmallKhmerFont)
		self.PantHipLabel.setObjectName("PantHipLabel")
		self.PantGroupLayout.addWidget(self.PantHipLabel, 2, 0, 1, 1)

		self.AnkleLabel = QtWidgets.QLabel(self.PantGroupBox)
		self.AnkleLabel.setFont(SmallKhmerFont)
		self.AnkleLabel.setObjectName("AnkleLabel")
		self.PantGroupLayout.addWidget(self.AnkleLabel, 9, 0, 1, 1)

		self.ThighBox = QtWidgets.QLineEdit(self.PantGroupBox)
		self.ThighBox.setAlignment(QtCore.Qt.AlignCenter)
		self.ThighBox.setObjectName("ThighBox")
		self.PantGroupLayout.addWidget(self.ThighBox, 7, 1, 1, 1)
		
		self.PantWaistLabel = QtWidgets.QLabel(self.PantGroupBox)
		self.PantWaistLabel.setFont(SmallKhmerFont)
		self.PantWaistLabel.setObjectName("label")
		self.PantGroupLayout.addWidget(self.PantWaistLabel, 1, 0, 1, 1)

		self.PantHipBox = QtWidgets.QLineEdit(self.PantGroupBox)
		self.PantHipBox.setAlignment(QtCore.Qt.AlignCenter)
		self.PantHipBox.setObjectName("PantHipBox")
		self.PantGroupLayout.addWidget(self.PantHipBox, 2, 1, 1, 1)

		self.AnkleBox = QtWidgets.QLineEdit(self.PantGroupBox)
		self.AnkleBox.setAlignment(QtCore.Qt.AlignCenter)
		self.AnkleBox.setObjectName("AnkleBox")
		self.PantGroupLayout.addWidget(self.AnkleBox, 9, 1, 1, 1)

		self.CalfBox = QtWidgets.QLineEdit(self.PantGroupBox)
		self.CalfBox.setAlignment(QtCore.Qt.AlignCenter)
		self.CalfBox.setObjectName("CalfBox")
		self.PantGroupLayout.addWidget(self.CalfBox, 8, 1, 1, 1)

		self.PantWaistBox = QtWidgets.QLineEdit(self.PantGroupBox)
		self.PantWaistBox.setAlignment(QtCore.Qt.AlignCenter)
		self.PantWaistBox.setObjectName("PantWaistBox")
		self.PantGroupLayout.addWidget(self.PantWaistBox, 1, 1, 1, 1)

		self.CmInseam = QtWidgets.QLabel(self.PantGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmInseam.sizePolicy().hasHeightForWidth())
		self.CmInseam.setSizePolicy(sizePolicy)
		
		self.CmInseam.setFont(ENGFont)
		self.CmInseam.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmInseam.setAutoFillBackground(False)
		self.CmInseam.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmInseam.setObjectName("CmInseam")
		self.PantGroupLayout.addWidget(self.CmInseam, 3, 2, 1, 1)

		self.CmPantHip = QtWidgets.QLabel(self.PantGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmPantHip.sizePolicy().hasHeightForWidth())
		self.CmPantHip.setSizePolicy(sizePolicy)
		
		self.CmPantHip.setFont(ENGFont)
		self.CmPantHip.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmPantHip.setAutoFillBackground(False)
		self.CmPantHip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmPantHip.setObjectName("CmPantHip")
		self.PantGroupLayout.addWidget(self.CmPantHip, 2, 2, 1, 1)
		self.CmPantWaist = QtWidgets.QLabel(self.PantGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmPantWaist.sizePolicy().hasHeightForWidth())
		self.CmPantWaist.setSizePolicy(sizePolicy)
		
		self.CmPantWaist.setFont(ENGFont)
		self.CmPantWaist.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmPantWaist.setAutoFillBackground(False)
		self.CmPantWaist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmPantWaist.setObjectName("CmPantWaist")
		self.PantGroupLayout.addWidget(self.CmPantWaist, 1, 2, 1, 1)
		self.CmOutseam = QtWidgets.QLabel(self.PantGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmOutseam.sizePolicy().hasHeightForWidth())
		self.CmOutseam.setSizePolicy(sizePolicy)
		
		self.CmOutseam.setFont(ENGFont)
		self.CmOutseam.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmOutseam.setAutoFillBackground(False)
		self.CmOutseam.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmOutseam.setObjectName("CmOutseam")
		self.PantGroupLayout.addWidget(self.CmOutseam, 6, 2, 1, 1)
		self.CmThigh = QtWidgets.QLabel(self.PantGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmThigh.sizePolicy().hasHeightForWidth())
		self.CmThigh.setSizePolicy(sizePolicy)
		
		self.CmThigh.setFont(ENGFont)
		self.CmThigh.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmThigh.setAutoFillBackground(False)
		self.CmThigh.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmThigh.setObjectName("CmThigh")
		self.PantGroupLayout.addWidget(self.CmThigh, 7, 2, 1, 1)
		self.CmCalf = QtWidgets.QLabel(self.PantGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmCalf.sizePolicy().hasHeightForWidth())
		self.CmCalf.setSizePolicy(sizePolicy)
		
		self.CmCalf.setFont(ENGFont)
		self.CmCalf.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmCalf.setAutoFillBackground(False)
		self.CmCalf.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmCalf.setObjectName("CmCalf")
		self.PantGroupLayout.addWidget(self.CmCalf, 8, 2, 1, 1)
		self.CmAnkle = QtWidgets.QLabel(self.PantGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(70)
		sizePolicy.setVerticalStretch(80)
		sizePolicy.setHeightForWidth(self.CmAnkle.sizePolicy().hasHeightForWidth())
		self.CmAnkle.setSizePolicy(sizePolicy)
		
		self.CmAnkle.setFont(ENGFont)
		self.CmAnkle.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.CmAnkle.setAutoFillBackground(False)
		self.CmAnkle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.CmAnkle.setObjectName("CmAnkle")
		self.PantGroupLayout.addWidget(self.CmAnkle, 9, 2, 1, 1)

		'''
		START OF connect slots and signals
		'''
		self.DateIcon.clicked.connect(self.EditDate)
		'''
		END OF connect slots and signals
		'''
		
		

		#raising -> divide this into functions
		#disable to not show in UI, used to get correct date format to database
		self.DeadlineBox.raise_()
		self.textBrowser_7.raise_()
		self.textBrowser_6.raise_()
		self.textBrowser_5.raise_()
		self.textBrowser_4.raise_()
		
		self.StaffNameBox.raise_()
		self.DeadlineSelectedLabel.raise_()
		self.DateIcon.raise_()
		self.ShirtDressSkirtBox.raise_()
		self.StaffTitle.raise_()
		self.PhoneLabel.raise_()
		self.DeadlineLabel.raise_()
		self.MeasurementTitle.raise_()
		self.CustomerInfoTitle.raise_()
		self.ColorLabel.raise_()
		self.StaffNameLabel.raise_()
		self.StyleLabel.raise_()
		self.MaterialsLabel.raise_()
		self.AddressLabel.raise_()
		self.CustomerNameLabel.raise_()
		self.CustomerPreferencesTitle.raise_()
		self.Cancel.raise_()
		self.Submit.raise_()
		self.PriceBox.raise_()
		self.PriceLabel.raise_()
		self.line.raise_()
		self.SpecialReqTitle.raise_()
		self.PreviewTitle.raise_()
		self.ShirtRadio.raise_()
		self.DressRadio.raise_()
		self.PantRadio.raise_()
		self.line_2.raise_()
		self.SkirtRadio.raise_()
		self.CustomerNameBox.raise_()
		self.PhoneBox.raise_()
		self.AddressBox.raise_()
		self.ColorBox.raise_()
		self.StyleBox.raise_()
		self.MaterialBox.raise_()
		self.SpecialReqBox.raise_()
		self.PantGroupBox.raise_()

		'''
		START OF MEASUREMENTS BOX
		'''

		#menu bar
		MainWindow.setCentralWidget(self.centralwidget)
		
		

		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 20))
		self.menubar.setObjectName("menubar")

		self.MenuNewOrder = QtWidgets.QMenu(self.menubar)
		self.MenuNewOrder.setObjectName("MenuNewOrder")
		self.MenuNewOrder.setFont(SmallKhmerFont)

		self.MenuAbout = QtWidgets.QMenu(self.menubar)
		self.MenuAbout.setObjectName("MenuAbout")
		self.MenuAbout.setFont(SmallKhmerFont)
		
		self.MenuView = QtWidgets.QMenu(self.menubar)
		self.MenuView.setObjectName("MenuView")
		self.MenuView.setFont(SmallKhmerFont)

		#action 
		self.actionNew = QtWidgets.QAction(MainWindow)
		self.actionNew.setObjectName("actionNew")
		self.actionNew.setFont(SmallKhmerFont)
		self.actionNew = QtWidgets.QAction(MainWindow)
		
		self.actionAll_Orders = QtWidgets.QAction(MainWindow)
		self.actionAll_Orders.setObjectName("actionAll_Orders")
		

		
		#u need to connect each menu option to an action 
		MainWindow.setMenuBar(self.menubar)
		''''
		self.statusBar = QtWidgets.QStatusBar(MainWindow)
		self.statusBar.setObjectName("statusBar")
		MainWindow.setStatusBar(self.statusBar)
		'''

		
		#connection action and button 
		
	
		#set menu bar functions
		
		self.actionNew.triggered.connect(self.clearInput)


		self.menubar.addAction(self.MenuNewOrder.menuAction())
		self.menubar.addAction(self.MenuView.menuAction())
		self.menubar.addAction(self.MenuAbout.menuAction())
		
		self.retranslateUi(MainWindow)

		#connect radio buttons and pictures
		self.ShirtRadio.toggled.connect(self.select_pic)
		self.DressRadio.toggled.connect(self.select_pic)
		self.PantRadio.toggled.connect(self.select_pic)
		self.SkirtRadio.toggled.connect(self.select_pic)

		#add widgets for 4 pictures

		self.RadioPicLabel = QtWidgets.QLabel(self.centralwidget)
		self.RadioPicLabel.setGeometry(QtCore.QRect(1100, 150, 621, 531))
		self.RadioPicLabel.setObjectName("RadioPicLabel")

		
		#self.Submit.clicked.connect(self.sendCustomerDetails)
		#self.Submit.clicked.connect(self.test)
		#self.Submit.clicked.connect(self.getCustomerDetails)

		QtCore.QMetaObject.connectSlotsByName(MainWindow)
	
	
	def select_pic(self):
		#_translate = QtCore.QCoreApplication.translate
		radioBtn = self.centralwidget.sender()

		if radioBtn.isChecked():
		
			
			if (radioBtn.text() == "សំពត់"):
				#skirt
				

				self.RadioPicLabel.setStyleSheet("\n""image: url(:/newPrefix/skirt.jpg);")
				
				
				'''
				self.skirtwidthpic.setGeometry(QtCore.QRect(1200, 610, 81, 31))
				self.skirtwidthpic.setObjectName("skirtwidthpic")
				

				self.skirtwidthpic.show()
		
				

				#set readonly in boxes we don't need for skirt
				
			

				self.BustHeightBox.setReadOnly(True)
				self.BustHeightBox.setStyleSheet("QLineEdit"
								"{"
								"background : grey;"
								"}") 
				'''
				#above is sample 

			elif (radioBtn.text() == "រ៉ូប"):
					#dress
				
				self.RadioPicLabel.setStyleSheet("\n""image: url(:/newPrefix/dress.jpg);")

				
				
			elif (radioBtn.text() == "អាវ"):
				#shirt
				self.RadioPicLabel.setStyleSheet("\n""image: url(:/newPrefix/shirt.jpg);")

			

			elif (radioBtn.text() == "ខោ"):
					#pant
				self.RadioPicLabel.setStyleSheet("\n""image: url(:/newPrefix/pant.jpg);")
				

	def test(self):
		print('yay')
		text = self.CustomerNameBox.text()
		print(text)

	def checkRequiredInputs(self): 
		
		#customer 
		customer_name = self.CustomerNameBox.text()
		address = self.AddressBox.text()
		telephone = self.PhoneBox.text()

		#order
		price = self.PriceBox.text()
		customer_name = self.CustomerNameBox.text()
		staff = self.StaffNameBox.text()
		#date_ordered = day+'/'+month+'/'+year
		deadline = self.DeadlineBox.text()
		#print(deadline)
		progress = '0'
		req = self.SReq.toPlainText()
		#print(req)
		#get customer ID                            

		if (price == "" or customer_name == "" or deadline == "" or telephone == ""): 
			self.feedbackSubmit(0)
			if price == "": 
				self.PriceLabel.setStyleSheet("color: red; background-color: light grey") 
			if customer_name == "":
				self.CustomerNameLabel.setStyleSheet("color: red; background-color: #d7dbdd") 
			if deadline == "":
				self.DeadlineLabel.setStyleSheet("color: red; background-color: #d7dbdd") 
			if telephone == "":
				self.PhoneLabel.setStyleSheet("color: red; background-color: #d7dbdd") 
			#self.status = 0

		else: 
			self.feedbackSubmit(1)
			self.PriceLabel.setStyleSheet("color: black; background-color: light grey") 
			self.CustomerNameLabel.setStyleSheet("color: black; background-color: #d7dbdd") 
			self.DeadlineLabel.setStyleSheet("color: black; background-color: #d7dbdd") 
			self.PhoneLabel.setStyleSheet("color: black; background-color: #d7dbdd") 
			self.DeadlineSelectedLabel.setStyleSheet("color: black; background-color: white") 
			self.complete_input = 1
			print("completed")
			
			'''
			#insert to table
			self.insertCustomerDetails()
			self.insertOrderDetails()
			'''
		#return self.status

	def insertCustomerDetails(self):

		if (self.complete_input == 1): 
			customer_name = self.CustomerNameBox.text()
			address = self.AddressBox.text()
			telephone = self.PhoneBox.text()
			insertCustomer(customer_name, address, telephone)
			self.added_customer = 1

		'''
		if customer_name == "" or telephone == "": 
			self.feedbackSubmit(0)
		else: 
			#insert customer details to customer table
			insertCustomer(customer_name, address, telephone)
			self.feedbackSubmit(1)
		'''

	def insertOrderDetails(self): 

		if ((self.complete_input == 1) and (self.added_customer == 1)): 
			
			price = self.PriceBox.text()
			customer_name = self.CustomerNameBox.text()
			staff = self.StaffNameBox.text()
			
			deadline = self.DeadlineBox.text()
			
			progress = '1'
			req = self.SReq.toPlainText()
			
			#get customer ID
			customer_id = getCustomerID()
			
			insertOrder(price, customer_name, staff, deadline, progress, customer_id, req)
		
		'''
		if price == "" or customer_name == "" or deadline == "": 
			self.feedbackSubmit(0)
		else: 
			#insert customer details to customer table
			customer_id = getCustomerID()
			insertOrder(price, customer_name, staff, deadline, progress, customer_id, req)
			self.feedbackSubmit(1)
		#insert order details into order table
		'''

	def feedbackSubmit(self, completed): 
		_translate = QtCore.QCoreApplication.translate
		
		#clear old message
		self.submit_msg.setText(_translate("MainWindow", ""))
		
		if (completed): 
			self.submit_msg.setText(_translate("MainWindow", "ប្រតិបត្តិការជោគជ័យ!"))
		elif (completed == 0) : 
			self.submit_msg.setText(_translate("MainWindow", "ប្រតិបត្តិការបរាជ័យ!សូមបំពេញព័ត៍មានបន្ថែម"))

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.StaffTitle.setText(_translate("MainWindow", "ព័ត៌មានបុគ្គលិក"))
		self.PhoneLabel.setText(_translate("MainWindow", "លេខទូរស័ព្ទ:"))
		self.DeadlineLabel.setText(_translate("MainWindow", "កាលបរិច្ឆេទ:"))
		self.MeasurementTitle.setText(_translate("MainWindow", "ការវាស់វែងអតិថិជន"))
		self.CustomerInfoTitle.setText(_translate("MainWindow", "ព័ត៌មានអតិថិជន"))
		self.ColorLabel.setText(_translate("MainWindow", "ពណ៌:"))
		self.StaffNameLabel.setText(_translate("MainWindow", "ឈ្មោះ:"))
		self.StyleLabel.setText(_translate("MainWindow", "រចនាបទ:"))
		self.MaterialsLabel.setText(_translate("MainWindow", "ប្រភេទក្រណាត់:"))
		self.AddressLabel.setText(_translate("MainWindow", "ឤស័យដ្ឋាន:"))
		self.CustomerNameLabel.setText(_translate("MainWindow", "ឈ្មោះ:"))
		self.CustomerPreferencesTitle.setText(_translate("MainWindow", "ជម្រើសអតិធិជន"))
		self.Cancel.setText(_translate("MainWindow", "លុបចោលការកម្មង់"))
		self.Submit.setText(_translate("MainWindow", "បំពេញរួចរាល់"))
		self.PriceBox.setText(_translate("MainWindow", "$"))
		self.PriceLabel.setText(_translate("MainWindow", "តម្លៃ:"))
		self.ShirtDressSkirtBox.setTitle(_translate("MainWindow", "អាវ រ៉ូប​ និងសំពត់"))
		self.DressSkirtWaistLabel.setText(_translate("MainWindow", "ជំុវិញចង្កេះ:"))
		self.CmUpperHips.setText(_translate("MainWindow", "cm"))
		self.UpperHipsLabel.setText(_translate("MainWindow", "ជំុវិញត្រគៀកអាវ:"))
		self.CmAroundBust.setText(_translate("MainWindow", "cm"))
		self.HipLabel.setText(_translate("MainWindow", "ត្រគៀកសំពត់:"))
		self.CmCenterFront.setText(_translate("MainWindow", "cm"))
		self.CmNeckArmHold.setText(_translate("MainWindow", "cm"))
		self.NeckArmHoldLabel.setText(_translate("MainWindow", "ជំុវិញកអាវ:"))
		self.CmAB.setText(_translate("MainWindow", "cm"))
		self.CmHip.setText(_translate("MainWindow", "cm"))
		self.CmBustHeight.setText(_translate("MainWindow", "cm"))
		self.CmAboveBust.setText(_translate("MainWindow", "cm"))
		self.CmSkirtLength.setText(_translate("MainWindow", "cm"))
		self.CmAF.setText(_translate("MainWindow", "cm"))
		self.CmShoulder.setText(_translate("MainWindow", "cm"))
		self.ShoulderLabel.setText(_translate("MainWindow", "ស្មា:"))
		self.CmCenterBack.setText(_translate("MainWindow", "cm"))
		self.CenterFrontLabel.setText(_translate("MainWindow", "គល់កមុខដល់ចង្កេះ:"))
		self.CmDressSkirtWaist.setText(_translate("MainWindow", "cm"))
		self.SleeveLengthLabel.setText(_translate("MainWindow", "សំរុងដៃអាវ:"))
		self.CmSleeveLength.setText(_translate("MainWindow", "cm"))
		self.AboveBustLabel.setText(_translate("MainWindow", "ទ្រូងលើ:"))
		self.CmArmPit.setText(_translate("MainWindow", "cm"))
		self.ArmpitLabel.setText(_translate("MainWindow", "រង្វងគល់ក្លៀក:"))
		self.ABLabel.setText(_translate("MainWindow", "សន្ទះក្រោយ:"))
		self.AroundBustLabel.setText(_translate("MainWindow", "ជំុវិញទ្រូង:"))
		self.BustHeightLabel.setText(_translate("MainWindow", "កំពស់ដើមទ្រូង:"))
		self.SkirtLengthLabel.setText(_translate("MainWindow", "សំរុងសំពត់:"))
		self.AFLabel.setText(_translate("MainWindow", "សន្ទះមុខ:"))
		self.CenterBackLabel.setText(_translate("MainWindow", "គល់កក្រោយដល់ចង្កេះ:"))
		self.SpecialReqTitle.setText(_translate("MainWindow", "សំណើពិសេស:"))
		self.PreviewTitle.setText(_translate("MainWindow", "រូបគំរូ"))
		self.ShirtRadio.setText(_translate("MainWindow", "អាវ"))
		self.DressRadio.setText(_translate("MainWindow", "រ៉ូប"))
		self.PantRadio.setText(_translate("MainWindow", "ខោ"))
		
		self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
	"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
	"p, li { white-space: pre-wrap; }\n"
	"</style></head><body style=\" SmallKhmerFont-family:\'MS Shell Dlg 2\'; SmallKhmerFont-size:8.25pt; SmallKhmerFont-weight:400; SmallKhmerFont-style:normal;\" bgcolor=\"#d7dbdd\">\n"
	"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
		self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
	"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
	"p, li { white-space: pre-wrap; }\n"
	"</style></head><body style=\" SmallKhmerFont-family:\'MS Shell Dlg 2\'; SmallKhmerFont-size:8.25pt; SmallKhmerFont-weight:400; SmallKhmerFont-style:normal;\" bgcolor=\"#d7dbdd\">\n"
	"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
		self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
	"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
	"p, li { white-space: pre-wrap; }\n"
	"</style></head><body style=\" SmallKhmerFont-family:\'MS Shell Dlg 2\'; SmallKhmerFont-size:8.25pt; SmallKhmerFont-weight:400; SmallKhmerFont-style:normal;\" bgcolor=\"#d7dbdd\">\n"
	"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
		self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
	"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
	"p, li { white-space: pre-wrap; }\n"
	"</style></head><body style=\" SmallKhmerFont-family:\'MS Shell Dlg 2\'; SmallKhmerFont-size:8.25pt; SmallKhmerFont-weight:400; SmallKhmerFont-style:normal;\" bgcolor=\"#d7dbdd\">\n"
	"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
		
		self.SkirtRadio.setText(_translate("MainWindow", "សំពត់"))
		self.PantGroupBox.setTitle(_translate("MainWindow", "ខោ"))
		self.ThighLabel.setText(_translate("MainWindow", "ទំហំភ្លៅ:"))
		self.OutseamLabel.setText(_translate("MainWindow", "សំរុងខោ:"))
		self.CalfLabel.setText(_translate("MainWindow", "កំភួនជើង:"))
		self.InseamLabel.setText(_translate("MainWindow", "សំរុងក្រលាន:"))
		self.PantHipLabel.setText(_translate("MainWindow", "ជំុវិញត្រកៀកខោ:"))
		self.AnkleLabel.setText(_translate("MainWindow", "កជើង:"))
		self.PantWaistLabel.setText(_translate("MainWindow", "ជុំវិញចង្កេះ:"))
		self.CmInseam.setText(_translate("MainWindow", "cm"))
		self.CmPantHip.setText(_translate("MainWindow", "cm"))
		self.CmPantWaist.setText(_translate("MainWindow", "cm"))
		self.CmOutseam.setText(_translate("MainWindow", "cm"))
		self.CmThigh.setText(_translate("MainWindow", "cm"))
		self.CmCalf.setText(_translate("MainWindow", "cm"))
		self.CmAnkle.setText(_translate("MainWindow", "cm"))
		self.DeadlineSelectedLabel.setText(_translate("MainWindow", 'សូមចុចរូបប្រតិទិន'))
		self.DeadlineSelectedLabel.setStyleSheet("color: black; background-color: white")

		#menu buttons
		self.MenuNewOrder.setTitle(_translate("MainWindow", "កម្មង់ថ្មី"))
		self.MenuAbout.setTitle(_translate("MainWindow", "កម្មវិធី"))
		self.MenuView.setTitle(_translate("MainWindow", "មើលការកម្មង់ទាំងអស់"))

		#use to connect with menu button
		#self.actionNew.setText(_translate("MainWindow", "កម្មង់ថ្មី11111"))
		self.actionAll_Orders.setText(_translate("MainWindow", "All Orders"))
		
		

		#color
		

		#self.DeadlineBox.setText(_translate("MainWindow", 'សូមចុចរូបប្រតិទិន'))
	#@QtCore.pyqtSlot(int, int, int)
	def PrintDate(self, day, month, year):
		#print(day,month,year)
		_translate = QtCore.QCoreApplication.translate
		#change DeadlineSelectedLabel name to deadline later
		self.DeadlineSelectedLabel.setText(_translate("MainWindow", f'{day}/{month}/{year}'))
		self.DeadlineSelectedLabel.setStyleSheet("color: black; background-color: white") 
		#self.DeadlineLabel.setText(_translate("MainWindow", f'{day}/{month}/{year}'))
	def getDate(self, day, month, year): 
		_translate = QtCore.QCoreApplication.translate
		self.DeadlineBox.setText(_translate("MainWindow", f'{year}/{month}/{day}'))
		#self.DeadlineBox.setStyleSheet("color: black; background-color: white") 
		#deadline = str(year)+'/'+str(month)+'/'+str(day)
		#return deadline

	def EditDate(self):
		self.dialog = CalendarWindow()
		self.dialog.submitted.connect(self.PrintDate)
		#self.dialog.submitted.connect(self.insertOrderDetails)
		self.dialog.submitted.connect(self.getDate)
		self.dialog.show()

	def clearInput(self): 
		_translate = QtCore.QCoreApplication.translate
		self.StaffNameBox.setText(_translate("MainWindow", ''))
		self.colorbox.setText(_translate("MainWindow", ''))
		self.stylebox.setText(_translate("MainWindow", ''))
		
		self.PhoneBox.setText(_translate("MainWindow", ''))
		self.AddressBox.setText(_translate("MainWindow", ''))
		self.materialbox.setText(_translate("MainWindow", ''))
		self.PriceBox.setText(_translate("MainWindow", ''))
		self.CIDbox.setText(_translate("MainWindow", ''))
		self.DeadlineBox.setText(_translate("MainWindow", 'សូមចុចរូបប្រតិទិន'))
		self.submit_msg.setText(_translate("MainWindow", ''))
		self.SReq.setPlainText(_translate("MainWindow", ''))


		self.PriceLabel.setStyleSheet("color: black; background-color: light grey") 
		self.CustomerNameLabel.setStyleSheet("color: black; background-color: #d7dbdd") 
		self.DeadlineLabel.setStyleSheet("color: black; background-color: #d7dbdd") 
		self.PhoneLabel.setStyleSheet("color: black; background-color: #d7dbdd") 
		self.DeadlineBox.setStyleSheet("color: black; background-color: white")
		
		

	# Create a Controller/Model class to connect the GUI and database
class appModel:
	"""model class."""
	def __init__(self, view):
		"""Controller initializer."""
		
		self._view = view
		# Connect signals and slots
		self._connectSignals()

		#interact with database here
	
	def _connectSignals(self):
		"""Connect signals and slots."""
		#trying to get Submit signal here
		#self._view.Submit.clicked.connect(self.sendCustomerDetails)
		#self._view.Submit.clicked.connect(lambda : print('here'))
		
		print(self._view.complete_input)
			
		self._view.Submit.clicked.connect(self._view.checkRequiredInputs)	
		
		self._view.Submit.clicked.connect(self._view.insertCustomerDetails)
		#insert to orders table 
		self._view.Submit.clicked.connect(self._view.insertOrderDetails)
		
		#print(self._view.status)
			


		self._view.Cancel.clicked.connect(self._view.clearInput)
		self._view.MenuNewOrder.triggered.connect(self._view.clearInput)
		#self._view.CustomerNameBox.textChanged.connect(textchanged)
			 
		

	#connect view buttons with database

	def insertCustomer(customer_name, address, telephone):
		'''insert customer details to customer tables'''
		#add 1 entry to table
		table = 'customers'
		postgres_insert_query = 'INSERT INTO %s (customer_name, address, telephone) VALUES (%s,%s,%s)'
		record_to_insert = (AsIs(table), customer_name, address, telephone,)
		cursor.execute(postgres_insert_query, record_to_insert)
		connection.commit()
		count = cursor.rowcount
		print(count, "Record inserted successfully into customers table")

	def insertOrder(price, customer_name, staff, deadline, progress, customer_id, req):
		'''insert Order details to Order tables'''
		table = 'orders'

		
		#add 1 entry to table
		postgres_insert_query = 'INSERT INTO %s (price, customer_name, staff, deadline, progress, customer_id, requests) VALUES (%s,%s,%s,%s,%s,%s,%s)'
		record_to_insert = (AsIs(table), price, customer_name, staff, deadline, progress, customer_id, req)
		cursor.execute(postgres_insert_query, record_to_insert)
		connection.commit()
		count = cursor.rowcount
		print(count, "Record inserted successfully into orders table")

	def getCustomerID(): 
	
	#helper function to include customer id into orders table
	#table = 'customers'
	#add 1 entry to table
		postgres_getID_query = 'SELECT currval(pg_get_serial_sequence(%s,%s))'
		record_to_getID = ('customers', 'ID')
		cursor.execute(postgres_getID_query, record_to_getID)
		customerID = cursor.fetchone()
		print(customerID, 'is customer ID for this order')
		return customerID




class CalendarWindow(QDialog):
	global currentYear, currentMonth, currentDay

	currentDay = datetime.now().day
	currentMonth = datetime.now().month
	currentYear = datetime.now().year

	submitted = QtCore.pyqtSignal(int, int, int)

	# constructor
	def __init__(self):
		super(CalendarWindow, self).__init__()
		self.setWindowTitle('Calendar')
		self.setGeometry(300, 300, 450, 300)
		self.setMinimumSize(QtCore.QSize(450, 300))
		self.setMaximumSize(QtCore.QSize(450, 300))
		self.initUI()
		self.setWindowModality(QtCore.Qt.ApplicationModal)

	def initUI(self):
		self.calendar = QCalendarWidget(self)
		self.calendar.move(20, 20)
		self.calendar.setGridVisible(True)

		#self.calendar.setMinimumDate(QDate(currentYear, currentMonth - 1, currentDay))
		#self.calendar.setMaximumDate(QDate(
		#	currentYear, currentMonth + 1, calendar.monthrange(currentYear, currentMonth)[1]))

		
		self.calendar.setSelectedDate(QDate(currentYear, currentMonth, currentDay))
		self.datelabel = QtWidgets.QLabel(self)
		self.datelabel.resize(200, 20) 
		date = self.calendar.selectedDate()
		self.datelabel.setText(date.toString())
		self.datelabel.move(20, 220)
		self.calendar.clicked.connect(self.sendDateMainWindow)

	def sendDateMainWindow(self, qDate):
		date = self.calendar.selectedDate()
		self.datelabel.setText(date.toString())
		
		self.submitted.emit(
			qDate.day(), qDate.month(), qDate.year()
			
		)



if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()


	#QtCore.Qt.AA_DisableHighDpiScaling
	#show GUI
ui = Ui_MainWindow()
ui.setupUi(MainWindow)

MainWindow.show()
	# Create instances of the model/controller
appModel(view=ui)

app.exec_()

close_connection(connection, cursor)
sys.exit()
